name       : vpnc
version    : 0.5.3
release    : 2
source     :
    - https://www.unix-ag.uni-kl.de/~massar/vpnc/vpnc-0.5.3.tar.gz : 46cea3bd02f207c62c7c6f2f22133382602baeda1dc320747809e94881414884
license    : GPL-2.0
summary    : client for cisco vpn concentrator
description: |
    client for cisco vpn concentrator
setup      :
    sed -i 's|^#OPENSSL|OPENSSL|g' Makefile
build      : |
    %make
install    : |
    %make_install PREFIX=/usr SBINDIR=/usr/bin
    install -m 00755 $pkgfiles/vpnc-script $installdir/etc/vpnc/vpnc-script
